version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "12345"]
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: "12345"
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  sonarqube:
    image: sonarqube:latest
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensins:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/sonarqube_logs
    ports:
      - "9000:9000"
  sonarqube-db:
    image: postgres:latest
    hostname: sonarqube-db
    container_name: sonarqube-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data
      - sonarqube_db:/var/lib/postgresql/data

volumes:
  db-data:
  pgadmin-data:
  sonarqube_data:
  sonarqube_extensins:
  sonarqube_logs:
  sonarqube_db_data:
  sonarqube_db: