// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package admin

import (
	"gorm.io/gorm"
	"sso-go-gin/config"
	"sso-go-gin/internal/admin/register_client/handler"
	"sso-go-gin/internal/admin/register_client/repository"
	"sso-go-gin/internal/admin/register_client/service"
)

// Injectors from wire.go:

func InitializeAdminHandlers(cfg *config.Config, db *gorm.DB) (*AdminHandlers, error) {
	registerRepository := repository.NewRegisterRepository(db)
	registerService := service.NewRegisterService(registerRepository)
	registerHandler := handler.NewRegisterHandler(registerService)
	adminHandlers := &AdminHandlers{
		RegisterHandler: registerHandler,
	}
	return adminHandlers, nil
}

// wire.go:

type AdminHandlers struct {
	RegisterHandler *handler.RegisterHandler
}
