// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"sso-go-gin/config"
	"sso-go-gin/internal/sso"
	"sso-go-gin/internal/sso/handler"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*gin.Engine, error) {
	ssoHandlers, err := sso.InitializeSSOHandlers(cfg)
	if err != nil {
		return nil, err
	}
	engine := newRouter(ssoHandlers)
	return engine, nil
}

// wire.go:

func newRouter(h *handler.SSOHandlers) *gin.Engine {
	r := gin.Default()

	ssoGroup := r.Group("/sso")
	handler.RegisterSSORoutes(ssoGroup, h)

	return r
}
