// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"sso-go-gin/internal/features/login"
	"sso-go-gin/internal/features/register"
	"sso-go-gin/internal/pkg/database"
)

// Injectors from wire.go:

func InitializeLoginHandler() (*login.Handler, error) {
	db, err := database.NewDB()
	if err != nil {
		return nil, err
	}
	repository := login.NewRepository(db)
	service := login.NewService(repository)
	handler := login.NewHandler(service)
	return handler, nil
}

func InitializeRegisterHandler() (*register.Handler, error) {
	db, err := database.NewDB()
	if err != nil {
		return nil, err
	}
	repository := register.NewRepository(db)
	service := register.NewService(repository)
	handler := register.NewHandler(service)
	return handler, nil
}
