// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package middleware

import (
	"gorm.io/gorm"
	"sso-go-gin/config"
	"sso-go-gin/internal/middleware/protect/handler"
	"sso-go-gin/internal/middleware/protect/repository"
	"sso-go-gin/internal/middleware/protect/service"
)

// Injectors from wire.go:

func InitializeMiddlewares(cfg *config.Config, db *gorm.DB) *Middlewares {
	protectRepository := repository.NewProtectRepository(db)
	protectService := service.NewProtectService(protectRepository)
	protectMiddleware := handler.NewProtectMiddleware(protectService)
	middlewares := &Middlewares{
		AdminOnlyMiddleware: protectMiddleware,
	}
	return middlewares
}

// wire.go:

type Middlewares struct {
	AdminOnlyMiddleware *handler.ProtectMiddleware
}
