// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package sso

import (
	"sso-go-gin/config"
	"sso-go-gin/internal/sso/handler"
	"sso-go-gin/internal/sso/repository"
	"sso-go-gin/internal/sso/service"
	"sso-go-gin/pkg/database"
)

// Injectors from wire.go:

func InitializeSSOHandlers(cfg *config.Config) (*handler.SSOHandlers, error) {
	db, err := database.NewDB(cfg)
	if err != nil {
		return nil, err
	}
	loginRepository := repository.NewLoginRepository(db)
	loginService := service.NewLoginService(loginRepository)
	loginHandler := handler.NewLoginHandler(loginService)
	ssoHandlers := &handler.SSOHandlers{
		Login: loginHandler,
	}
	return ssoHandlers, nil
}
